print("# John Lennon")
print("or ***John Winston Ono Lennon*** was one of *The Beatles*.")
print("Here are the songs he wrote I like the most:")
print("* Imagine")
print("* Norwegian Wood")
print("* Come Together")
print("* In My Life")
print("* ~~Hey Jude~~ (that was *McCartney*)")
